# Generated by Django 3.1.4 on 2020-12-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pov', models.CharField(max_length=20)),
                ('ff', models.CharField(max_length=100)),
                ('blog', models.TextField(max_length=15000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pic', models.ImageField(default='IMG', upload_to='images')),
            ],
        ),
    ]
